### ISSUE TITLE
No module named data_splitting

### ISSUE THREAD

**Issue by alighazi99** [inventec-ai-center/bp-benchmark#1]
Hi, When I run the following command:
```
 python process.py --config_file ./core/config/sensors_process.yaml
```
 I get this error

```
from data_splitting import main as split
ModuleNotFoundError: No module named 'data_splitting'
```

I am also not able to find the file 'data_splitting'

**Comment by alighazi99** [comment]
Just wanted to let you know I changed this line in process.py file
```
from read_sensors import main as split
```
and it executes.

**Comment by inventec-ai-center** [comment]
We have uploaded the data_splitting module. It keeps the samples from the same patient in the same fold, but it does not preserve BP distribution. Please refer to the paper (https://www.nature.com/articles/s41597-023-02020-6) for self-implementation or the split datasets (https://doi.org/10.6084/m9.figshare.c.6150390.v1) if you require this constraint.
