### ISSUE TITLE
about the prediction example

### ISSUE THREAD

**Issue by whucsu** [inventec-ai-center/bp-benchmark#6]
thanks for sharing the code.
Is there any prediction example ? as to load only one pice of ppg sign and predict the abp using the pretrain models ?

**Comment by sergiogvz** [comment]
Hi @whucsu!

Thanks for your interest in our research.

As the easiest example, I refer you to the [testing example in the README](https://github.com/inventec-ai-center/bp-benchmark?tab=readme-ov-file#testing). `python test.py --config_file core/config/test/dl/ts_unet_bcg.yaml` will yield a pickle file `prediction/bcg_dataset/bcg-unet1d.pkl` with the predictions of the pretrain models for 5fcv BCG dataset. You could modify the config file core/config/test/dl/ts_unet_bcg.yaml to load your dataset (fields 'exp' - 'subject_dict', 'N_fold', 'cv'). The prediction pickle file can be loaded with `joblib.load` and it is a dict with two keys: **out_metric** stores the evaluation metrics and **fold_errors** has the ground truth and predictions of each fold, including ID, ABP, SBP, and DBP. The following example plots the GT and predictions from a sample of the 1st fold. 

```python
import joblib
# Load with joblib
dic_res=joblib.load("prediction/bcg_dataset/bcg-unet1d.pkl")

# Evaluation metric results
print(dic_res['out_metric'])

# Here you will find the ground-truth and predictions of each fold for the test set, including the id, ABP, SBP, and DBP.
print(dic_res['fold_errors'].keys())

idx=40
plt.plot(dic_res['fold_errors']['test_abp_true'][0][idx])
plt.plot(dic_res['fold_errors']['test_abp_pred'][0][idx])
plt.show()

```

If this is not enough, you will need to get more familiar with the code. I would recommend following our code structure. The following code could serve as an example to work with the code. I am using a U-Net model pre-trained with a Sensor dataset to predict one fold of BCG data.

```python
import sys
from glob import glob
sys.path.append("./code/train")
from scipy.io import loadmat
from core.utils import  (cal_statistics, mat2df)
from core.models import MyTrainer
from omegaconf import OmegaConf
from core.solver_s2s import Solver as solver_s2s
import matplotlib.pyplot as plt

#--- Configuration file
config = OmegaConf.load('./code/train/core/config/test/dl/ts_unet_sensors.yaml')

#--- Solver
solver = solver_s2s(config)

#--- Compute statistics for normalization according to training dataset (sensors in this example)
all_split_df = [mat2df(loadmat(f"{solver.config.exp.subject_dict[4:]}_{i}.mat")) for i in range(solver.config.exp.N_fold)]
solver.config = cal_statistics(solver.config, all_split_df)

#--- Data module
dm = solver._get_loader()
test_df = mat2df(loadmat('./datasets/splitted/bcg_dataset/signal_fold_0.mat'))
dm.setup_kfold(test_df, test_df, test_df) # training and validation are not used for inference

#--- Model
model = solver._get_model(ckpt_path_abs='./models/model-unet1d/sensors-unet1d-fold4-test_sp=14.650-test_dp=7.417.ckpt')
model = model.eval()

#--- Trainer
trainer = MyTrainer()
trainer.model = model

#--- Inference
test_outputs = trainer.test(model=model, test_dataloaders=dm.test_dataloader(), verbose=True)

#--- Denormalize output
bp_denorm = dm.test_dataloader().dataset.bp_denorm
true_abps = bp_denorm(test_outputs["true_abp"].squeeze(1).numpy(), solver.config, 'abp')
pred_abps = bp_denorm(test_outputs["pred_abp"].squeeze(1).numpy(), solver.config, 'abp')

#--- Plot one of the output
plt.plot(true_abps[0])
plt.plot(pred_abps[0])
plt.show()

```
