### ISSUE TITLE
How about your work on MABP estimation?

### ISSUE THREAD

**Issue by ms-keliu** [inventec-ai-center/bp-benchmark#7]
I've noticed "process_MABP.py" in your project to calculate mean ABP value during a cycle, which is not mentioned in your paper. Can you describe your work related to MABP? Thank you for your attention:)

**Comment by sergiogvz** [comment]
Thank you for your interest in our work. The file process_MABP.py aims to preprocess the ABP signal to create the ground-truth output for the PPG2IABP model [12], which is the average ABP pulse (MABP) with some semantic segmentation (systolic phase, Systolic peak to Dicrotic Notch, Dicrotic Notch to the end). If I don't remember wrongly, the original preprocessing code of Aguirre et al.** was in Matlab code. Thus, we decided to reimplement it in Python to preprocess the different datasets in our benchmark. For more information about the procedure, I refer you to Aguirre's original paper [12] and code**.

Our MABP procedure follows the following steps:
1. Identification of each heart cycles in the ABP signal.
2. Fix the cycle size (limiting and padding)
3. Exclude cycles out of mean+-(1*25*std).
4. Compute average cycle.
5. Extract systolic peak and Dicrotic Notch.


[12] Aguirre, N., Grall-Maës, E., Cymberknop, L. J. & Armentano, R. L. Blood pressure morphology assessment from photoplethysmogram and demographic information using deep learning with attention mechanism. Sensors 21, 2167 (2021).
** https://github.com/AguirreNicolas/PPG2IABP/tree/main
